# Generated by Django 3.0.2 on 2020-03-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagstone', '0031_customercarf_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercarf',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=55.0, max_digits=5),
        ),
    ]
