# Generated by Django 3.0.2 on 2020-03-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagstone', '0032_auto_20200311_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercarf',
            name='reservation_status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Cancelled', 'Cancelled'), ('Paid-Self', 'Paid-Self'), ('Paid-Other', 'Paid-Other')], default='reserved', max_length=28),
        ),
        migrations.AlterField(
            model_name='customercarf',
            name='reservation_type',
            field=models.CharField(choices=[('One Way Arrival', 'One Way Arrival'), ('One Way Departure', 'One Way Departure'), ('Round Trip', 'Round Trip')], default='round_trip', max_length=28),
        ),
    ]
