# Generated by Django 3.0.2 on 2020-03-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagstone', '0033_auto_20200311_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercarf',
            name='email',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='customercarf',
            name='phone',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
