# Generated by Django 3.0.2 on 2020-03-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagstone', '0034_auto_20200311_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercarf',
            name='arrival_date',
            field=models.DateField(blank=True, default='2020-03-20', null=True),
        ),
        migrations.AlterField(
            model_name='customercarf',
            name='departure_date',
            field=models.DateField(blank=True, default='2020-03-22', null=True),
        ),
    ]
