# Generated by Django 3.0.2 on 2022-02-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flagstone', '0036_auto_20200311_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='affiliate_info',
        ),
    ]
