# Generated by Django 3.0.2 on 2022-02-24 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flagstone', '0037_remove_customer_affiliate_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='org_name',
        ),
        migrations.AlterField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flagstone.Customer'),
        ),
    ]
