# Generated by Django 3.0.2 on 2022-02-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagstone', '0038_auto_20220224_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='van',
            name='tag_exp',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
