# Generated by Django 3.0.2 on 2022-02-24 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flagstone', '0039_auto_20220224_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shuttle',
            name='org_name',
        ),
    ]
