# Generated by Django 3.0.2 on 2022-02-24 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flagstone', '0040_remove_shuttle_org_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shuttle',
            name='arrival_airline',
        ),
        migrations.RemoveField(
            model_name='shuttle',
            name='arrival_airport',
        ),
        migrations.RemoveField(
            model_name='shuttle',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='shuttle',
            name='arrival_flight',
        ),
        migrations.RemoveField(
            model_name='shuttle',
            name='arrival_notes',
        ),
        migrations.RemoveField(
            model_name='shuttle',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='shuttle',
            name='departing_notes',
        ),
        migrations.RemoveField(
            model_name='shuttle',
            name='departure_airline',
        ),
        migrations.RemoveField(
            model_name='shuttle',
            name='departure_airport',
        ),
        migrations.RemoveField(
            model_name='shuttle',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='shuttle',
            name='departure_flight',
        ),
        migrations.RemoveField(
            model_name='shuttle',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='shuttle',
            name='drop_location',
        ),
        migrations.RemoveField(
            model_name='shuttle',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='shuttle',
            name='pickup_time',
        ),
    ]
